package its340.finalproject;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultListModel;
import javax.swing.*;
import java.util.StringJoiner;

public class ActivityTolerance extends javax.swing.JFrame {

    public ActivityTolerance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        list_at = new javax.swing.JList<>();
        btn_retrievall = new javax.swing.JButton();
        lbl_atid = new javax.swing.JLabel();
        panel_nav = new javax.swing.JPanel();
        btn_formlock = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        btn_toDEM = new javax.swing.JButton();
        btn_toGMH = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_interview = new javax.swing.JButton();
        btn_toPS = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_dectolerance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_attime = new javax.swing.JTextField();
        txt_activity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_atdate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_actqty = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbl_patientid = new javax.swing.JLabel();
        lbl_patientname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list_at.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_atMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(list_at);

        btn_retrievall.setText("GET ALL RECORDS");
        btn_retrievall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retrievallActionPerformed(evt);
            }
        });

        lbl_atid.setText("AT ID:");

        panel_nav.setBackground(new java.awt.Color(0, 51, 102));

        btn_formlock.setText("EDIT MODE");
        btn_formlock.setName("btn_formlock"); // NOI18N
        btn_formlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formlockActionPerformed(evt);
            }
        });

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_new.setText("NEW");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_toDEM.setText("Demographics");
        btn_toDEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toDEMActionPerformed(evt);
            }
        });

        btn_toGMH.setText("Shortness of Breath");
        btn_toGMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toGMHActionPerformed(evt);
            }
        });

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_interview.setText("START INTERVIEW");
        btn_interview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_interviewActionPerformed(evt);
            }
        });

        btn_toPS.setText("Patient Select");
        btn_toPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toPSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_navLayout = new javax.swing.GroupLayout(panel_nav);
        panel_nav.setLayout(panel_navLayout);
        panel_navLayout.setHorizontalGroup(
            panel_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_toGMH, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(btn_toDEM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_formlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_interview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_toPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panel_navLayout.setVerticalGroup(
            panel_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_navLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btn_toGMH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_toDEM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_toPS)
                .addGap(39, 39, 39)
                .addComponent(btn_new)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save)
                .addGap(3, 3, 3)
                .addComponent(btn_delete)
                .addGap(46, 46, 46)
                .addComponent(btn_interview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(btn_formlock)
                .addGap(50, 50, 50))
        );

        jLabel23.setFont(new java.awt.Font("Bahnschrift", 0, 48)); // NOI18N
        jLabel23.setText("ACTIVITY TOLERANCE");

        jLabel6.setText("Activity Quantity:");

        txt_dectolerance.setText(" ");

        jLabel2.setText("Activity:");

        txt_activity.setText(" ");

        jLabel5.setText("Activity Date:");

        txt_atdate.setText(" ");

        jLabel3.setText("Activity Time:");

        txt_actqty.setText(" ");

        jLabel4.setText("Decreased Tolerance:");
        jLabel4.setToolTipText("");

        lbl_patientid.setText("Patient ID:");

        lbl_patientname.setText("Current Patient:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_dectolerance, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_atdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_attime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_patientname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_patientid, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_actqty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_activity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_patientname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_patientid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_atdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_attime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dectolerance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_activity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_actqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_atid, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_retrievall, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_atid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_retrievall)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_nav, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int atid;
    private void list_atMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_atMouseClicked
        int selectedRow = list_at.getSelectedIndex();
        if (selectedRow != -1)
        {
            String atidStr = list_at.getSelectedValue();
            String numberOnly = atidStr.replaceAll("[^0-9]", ""); //format for int
            atid = Integer.parseInt(numberOnly);
            lbl_atid.setText("AT ID: " + atid);
            System.out.println("DEBUG: Clicked Record ID: " + atidStr);

            try
            {
                Connection conn = GlobalData.ConnectToDB("root", "password");
                ResultSet rs = DBUtilsAT.GetATRecordFromATID(conn, atid);

                //fill textfields
                if (rs.next())
                {
                    //txt_box.setText(rs.getString(sqlColumnName));
                    txt_atdate.setText(rs.getString("ATDate"));
                    txt_attime.setText(rs.getString("ATTime"));
                    txt_dectolerance.setText(rs.getString("DecreasedTolerance"));
                    txt_activity.setText(rs.getString("Activity"));
                    txt_actqty.setText(rs.getString("ActivityQty"));
                }
                conn.close();
            }
            catch(Exception e)
            {
                System.out.println(e.getMessage() );
            }
        }
    }//GEN-LAST:event_list_atMouseClicked

    private void btn_retrievallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retrievallActionPerformed
        try
        {
            int pid = GlobalData.patientID;
            lbl_patientname.setText("Current Patient: " + GlobalData.patientName);
            lbl_patientid.setText("Patient ID: " + GlobalData.patientID);

            Connection conn = GlobalData.ConnectToDB("root", "password");
            ResultSet rs = DBUtilsAT.GetATRecordsFromPID(conn, pid);

            DefaultListModel lst = new DefaultListModel();
            while(rs.next() )
            {
                String listData = "RECORD NUMBER: " + rs.getString(1);
                lst.addElement(listData);
            }
            list_at.setModel(lst);
            conn.close();
        }
        catch (Exception e)
        {
            System.out.println(e.getMessage() );
        }
    }//GEN-LAST:event_btn_retrievallActionPerformed

    private void btn_formlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formlockActionPerformed
        boolean editMode = btn_formlock.getText().equals("VIEW MODE");
        DBUtils_General.toggleFormMode(getContentPane(), editMode);
    }//GEN-LAST:event_btn_formlockActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try
        {
            Connection conn = GlobalData.ConnectToDB("root", "password");
            
            Integer decTolerance = Integer.parseInt(txt_dectolerance.getText());
            Integer actqty = Integer.parseInt(txt_actqty.getText());
            
            DBUtilsAT.UpdateATRecord(conn, atid, txt_atdate.getText(), txt_attime.getText(),
                txt_activity.getText(), decTolerance,  actqty);

            conn.close();
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage() );
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed

        try
        {
            int pid = GlobalData.patientID;
            Connection conn = GlobalData.ConnectToDB("root", "password");
            
            Integer decTolerance = Integer.parseInt(txt_dectolerance.getText());
            Integer actqty = Integer.parseInt(txt_actqty.getText());
            DBUtilsAT.InsertATRecord(conn, pid, txt_atdate.getText(), txt_attime.getText(), 
                    txt_activity.getText(), decTolerance, actqty);
            //maybe add a confirmation swing popup here

            //retrieve all after inserting
            ResultSet rs = DBUtilsAT.GetATRecordsFromPID(conn, pid);

            DefaultListModel lst = new DefaultListModel();
            while(rs.next() )
            {
                String listData = "RECORD NUMBER: " + rs.getString(1);
                lst.addElement(listData);
            }
            list_at.setModel(lst);
            conn.close();
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage() );
        }
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_toDEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toDEMActionPerformed
        Demographics demFrame = new Demographics();
        demFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_toDEMActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try
        {
            Connection conn = GlobalData.ConnectToDB("root", "password");
            int pid = GlobalData.patientID;
            DBUtilsAT.DeleteATRecord(conn, atid);

            //retrieve all after deletion
            ResultSet rs = DBUtilsAT.GetATRecordsFromPID(conn, pid);
            DefaultListModel lst = new DefaultListModel();
            while(rs.next() )
            {
                String listData = "RECORD NUMBER: " + rs.getString(1);
                lst.addElement(listData);
            }
            list_at.setModel(lst);

            //clear text fields
            for (java.awt.Component comp : getContentPane().getComponents())
            {
                if (comp instanceof JTextField)
                {
                    ((JTextField) comp).setText("");
                }
            }
            conn.close();
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_interviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_interviewActionPerformed
        BuildTrees.BuildAllInterviewQuestionSets();
        
        Decision activityTree = GlobalData.ATQSet;
        activityTree.queryTree(activityTree.getRoot(), "activity");

        if (!GlobalData.ATResult.isEmpty()) {
            //"Understood, thank you for your time. Recorded: activity climb stairs, dectol 1, qty 10"
            String[] parts = GlobalData.ATResult.split("Recorded:")[1].trim().split(",");

            String activity = parts[0].replace("activity", "").trim(); 
            String dectol = parts[1].replace("dectol", "").trim(); 
            String qty = parts[2].replace("qty", "").trim(); 

            txt_activity.setText(activity);
            txt_dectolerance.setText(dectol);
            txt_actqty.setText(qty);
        }

    }//GEN-LAST:event_btn_interviewActionPerformed

    private void btn_toPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toPSActionPerformed
        PatientSelect psFrame = new PatientSelect();
        psFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_toPSActionPerformed

    private void btn_toGMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toGMHActionPerformed
        GeneralMedicalHistory gmhFrame = new GeneralMedicalHistory();
        gmhFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_toGMHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActivityTolerance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActivityTolerance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActivityTolerance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActivityTolerance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActivityTolerance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_formlock;
    private javax.swing.JButton btn_interview;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_retrievall;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_toDEM;
    private javax.swing.JButton btn_toGMH;
    private javax.swing.JButton btn_toPS;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_atid;
    private javax.swing.JLabel lbl_patientid;
    private javax.swing.JLabel lbl_patientname;
    private javax.swing.JList<String> list_at;
    private javax.swing.JPanel panel_nav;
    private javax.swing.JTextField txt_activity;
    private javax.swing.JTextField txt_actqty;
    private javax.swing.JTextField txt_atdate;
    private javax.swing.JTextField txt_attime;
    private javax.swing.JTextField txt_dectolerance;
    // End of variables declaration//GEN-END:variables
}
